### ISSUE TITLE
OSSMC graph does not work locally

### ISSUE THREAD

**Issue by ferhoyos** [kiali/openshift-servicemesh-plugin#231]
### Describe the bug

OSSMC graph does not work locally, throwing following error message:

```
main-chunk-ab2caeaac4b7213d2269.min.js:1 unhandled error: Uncaught Error: [mobx] There are multiple, different versions of MobX active. Make sure MobX is loaded only once or use `configure({ isolateGlobalState: true })` Error: [mobx] There are multiple, different versions of MobX active. Make sure MobX is loaded only once or use `configure({ isolateGlobalState: true })`
    at invariant (http://localhost:9000/api/plugins/ossmconsole/vendors-node_modules_patternfly_react-charts_dist_esm_components_ChartBar_ChartBar_js-node_mo-e96a7b-chunk.js:102016:15)
    at fail (http://localhost:9000/api/plugins/ossmconsole/vendors-node_modules_patternfly_react-charts_dist_esm_components_ChartBar_ChartBar_js-node_mo-e96a7b-chunk.js:102011:5)
    at http://localhost:9000/api/plugins/ossmconsole/vendors-node_modules_patternfly_react-charts_dist_esm_components_ChartBar_ChartBar_js-node_mo-e96a7b-chunk.js:103490:17 Error: [mobx] There are multiple, different versions of MobX active. Make sure MobX is loaded only once or use `configure({ isolateGlobalState: true })`
    at invariant (mobx.module.js:16:1)
    at fail (mobx.module.js:11:1)
    at mobx.module.js:1490:1
```

OSSMC works fine when it is installed through operator, so it only affects local development (it seems something related to patternfly...)

**Comment by ferhoyos** [comment]
Fixed via #232
